# Generated by Django 5.2.4 on 2025-07-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_customer_address_order_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_percent',
            field=models.CharField(choices=[('20', 'Đã thanh toán 20%'), ('100', 'Đã thanh toán 100%')], default='100', max_length=3),
        ),
    ]
