# Generated by Django 5.2.4 on 2025-07-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order_payment_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='online', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_percent',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
