# Generated by Django 5.2.4 on 2025-07-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_payment_method_alter_order_payment_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='place',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
