# Generated by Django 5.2.4 on 2025-07-13 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_contact_is_replied_contact_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='app.tour'),
        ),
    ]
