# Generated by Django 5.2.4 on 2025-07-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_orderitem_tour_code_orderitem_tour_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='ly_do_huy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
